### ISSUE TITLE
Error when handling orientation for mobile

### ISSUE THREAD

**Issue by adaoc** [orange-games/phaser-ts-boilerplate#1]
"Cannot read property 'style of null'" when setting LANDSCAPE_LOCKED or PORTRAIT_LOCKED to true in the Constants.ts. 

A quick fix is to add a div with an id 'orientation' to the index.html templates, though it doesn't seem to hide the 'orientation' div after rotating it back to the correct orientation.

**Comment by AleBles** [comment]
Should be there now =)

**Comment by adaoc** [comment]
Awesome, thank you!
