### ISSUE TITLE
Sound Manager toggle

### ISSUE THREAD

**Issue by OskarDawid** [orange-games/phaser-ts-boilerplate#7]
In our game we had music turned on while starting menu state. When musicOn(SaveGame.ts) value was saved as false, and game window refreshed, the toggleMusic(SoundManager.ts) method stopped working, and cache clean was needed to bring back music. It is becase 

 if (this.music) {
                 this.music.play(undefined, undefined, 1, true);
 } 

this if is never true, since this.music can never be set as true, because playMusic(SoundManager.ts) method is instant returning in if and key for music is always undefined

if (!Save.Game.getInstance().music) {
                return;
}

The fix (probably one of many) would be setting music key somewhere, so the if will get true, and music will be able to play (quick fix for me was setting with sound.play and instant stopping it, before return)

if (!Save.Game.getInstance().music) {
                this.music = this.sound.play(key, 1, true);
                this.music.stop();
                return;
}

(playMusic() in soundManager.ts)

**Comment by AleBles** [comment]
Should be fixed now in sound_fixes branch
